base/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'base'

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('about', views.about_page, name='about_page'),
    path('docs', views.docs_page, name='docs_page')
    # path('', TemplateView.as_view(template_name="home/home.html")),
]

drink_book/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from django.conf import settings
import environ
import os
import debug_toolbar

env = environ.Env()
environ.Env.read_env()

urlpatterns = [
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path(env('SECRET_ADMIN_URL') + '/admin/', admin.site.urls),
    path('', include('base.urls', namespace='base')),
    path('api/', include('cocktail_api.urls',  namespace='cocktail_api')),  # 'cocktail_api.urls',
    path('api/user/', include('accounts.urls', namespace='accounts')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('__debug__/', include(debug_toolbar.urls)),
   ]

templates/drink/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta property="og:title" content="Cocktails API">
    <meta property="og:type" content="website">
    <meta property="og:image" content="">
    <meta property="og:url" content="https://paulrblack.com/cocktailapi">
    <meta property="og:description" content="An API With the Names and Recipes for 100 popular cocktails">
    <meta property="og:local" content="en_US">
    <meta property="og:site_name" content="CocktailsAPI">
    <meta name="keywords" content="Cocktails Shots Drinks Alcohol Bar Restaurant">
    <meta name="author" content="Paul Black">
    <meta name="twitter:widgets:autoload" content="off">

    <link rel=canonical" href="/">
    <link rel="me" href="https://twitter.com/TwitterDev">

    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/index_responsive.css' %}">
    <link rel="stylesheet" href="{% static 'css/home/home.css' %}">
    <link rel="stylesheet" href="{% static 'css/home/home_responsive.css' %}">

    <link rel="stylesheet" href="{% static 'css/about/about.css' %}">
    <link rel="stylesheet" href="{% static 'css/docs/docs.css' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'img/favicon/site.webmanifest' %}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
</head>
<body>
    <nav class="navbar">
        <div class="container">
            <div class="inner_nav_container">
                <div class="navbar_logo_container">
                    <h2 class="logo" tabindex="-" aria-label="home logo"><a href="/">DrinksAPI</a></h2>
                </div>
                <div class="navbar_items">
                    <ul class="navbar_menu" data-visible="false">
                        <li class="navbar_item"><a class="navbar_links" href="/">Home</a></li>
                        <li class="navbar_item"><a class="navbar_links" href="{% url 'base:about_page' %}">About</a></li>
                        <li class="navbar_item"><a class="navbar_links" href="{% url 'base:docs_page' %}">Docs</a></li>
                        {% comment %}
                        <li class="navbar_item"><a class="navbar_links twitter-follow-button"  rel="me"  href="https://twitter.com/JuanJohn81" data-dnt="true"  target="_blank">Tweet</a></li>
                        {% endcomment %}
                    </ul>
                    <div class="hamburger_menu" id="mobile_menu" aria-controls="navbar_menu" aria-expanded="false">
                        <span class="bar sr-only"></span>
                        <span class="bar sr-only"></span>
                        <span class="bar sr-only"></span>
                    </div>
                </div>
            </div>
        </div>
    </nav>
{% block main %}

{% endblock %}
<footer>
    <div class="container">
        <div class="footer_container">
            <div class="navbar_logo">
                <h2 class="logo" tabindex="0" aria-label="home logo"><a href="/">DrinksAPI</a></h2>
                <a class="navbar_created" href="https://paulrblack.com">Created By: Paul B</a>
            </div>
            <div class="rights_reserved">
                <p>&copy; DrinksAPI<span class="rights_year"> {{ year }}.</span></p>
                <p>All Rights Reserved</p>
            </div>

            <div class="footer_link_block">
                <ul class="footer_menu">
                    <li class="footer_item">
                        <a class="footer_links" href="/">Home</a>
                    </li>
                    <li class="footer_item">
                        <a class="footer_links" href="{% url 'base:about_page' %}">About</a>
                    </li>
                     <li class="footer_item">
                        <a class="footer_links" href="{% url 'base:docs_page' %}">Docs</a>
                    </li>
                    {% comment %}
                    <li class="footer_item">
                        <a class="footer_links twitter-follow-button"  rel="me"  href="https://twitter.com/JuanJohn81" data-dnt="true" target="_blank">Tweet</a>
                    </li>
                    {% endcomment %}
                </ul>
            </div>
        </div>
    </div>
</footer>
<script src="{% static 'js/nav.js' %}"></script>
<script src="{% static 'js/serializedData.js' %}"></script>
</body>
</html>